### ISSUE TITLE
Referencing libsass outside of virtualenv (for libsass dependency)

### ISSUE THREAD

**Issue by sherwyngoh** [torchbox/django-libsass#11]
I have 64bit python installed, which means I needed the 64 bit version of libsass-python.
I got it and installed it, but was still presented by the 

"ImportError: DLL load failed: %1 is not a valid Win32 application"

error, which comes from django-sass not using the libsass-python installation I had input

I've resolved this issue locally but by installing libsass-python outside of the virtualenv.

**Comment by gasman** [comment]
I don't think there's anything django-libsass can do about libsass-python installation issues - all we do is install libsass-python as a dependency. If that's pulling in the wrong thing, then either your system is configured incorrectly, or there's a bug in libsass-python or the Python package tools.
