### ISSUE TITLE
Scss imports do not work with django-compressor 1.6

### ISSUE THREAD

**Issue by frgtn** [torchbox/django-libsass#16]
Since version 1.6 django-compressor does not pass filename to sass/scss file but instead invokes it by passing source as a string. Because no filename is not passed libsass has no way of knowing where to search for scss includes.

**Comment by gasman** [comment]
Have you tested this on the current master of django-libsass (or version 0.6, just released today)? There were some changes to method parameters in django-compressor 1.6, and if you're using django-libsass 0.5 it could look like it's passing a source string instead of a filename.

**Comment by frgtn** [comment]
Ha, didn't notice 0.6 came out, went straight to issues. Upgrading to 0.6 solved it, everything's working smoothly. Thanks!
