### ISSUE TITLE
Wrong font urls

### ISSUE THREAD

**Issue by potar** [torchbox/django-libsass#17]
I'm not sure why it happens but let me describe an issue I've faced. So, I installed the newest package versions:
* libsass-0.9.2
* django-libsass-0.6

After I detected on my site that fonts hadn't been downloaded due to wrong urls, therefore I checked css files and found font urls like:

```
url('https://d66cvws976y93.cloudfront.net/static/bower_components/bootstrap-sass/assets/fonts/bootstrap"glyphicons-halflings-regular.eot');
url('https://d66cvws976y93.cloudfront.net/static/bower_components/bootstrap-sass/assets/fonts/bootstrap"glyphicons-halflings-regular.eot?#iefix') 
```

Note, `"` in the middle of the urls, that's why I went back to the previous versions of packages that work for me:
* libsass-0.8.3
* django-libsass-0.4

**Comment by gasman** [comment]
What's the original line in the .scss file that's producing this output?

**Comment by gasman** [comment]
Closing due to lack of information - please reopen if you can provide the line of code that's producing this output.
