### ISSUE TITLE
Readme unclear

### ISSUE THREAD

**Issue by DanielTate** [torchbox/django-libsass#24]
Should I include anything in my installed apps?

What is the suggested way to set this up?

**Comment by kaedroho** [comment]
``django-libsass`` provides a precompiler class ``django-compressor`` so you only need to have the ``compressor`` app in ``INSTALLED_APPS``.

To enable ``django-libsass``, just add it to the ``COMPRESS_PRECOMPILERS`` setting (details in the readme).

**Comment by gasman** [comment]
Hi @DanielTate - the installation section in the readme gives specific instructions about what needs to be changed, so I'm not sure what we can really improve there. Which bits in particular are you finding unclear?

**Comment by DanielTate** [comment]
See this question
http://stackoverflow.com/questions/38862786/why-cant-django-see-my-static-files?noredirect=1#comment65125285_38862786

**Comment by gasman** [comment]
That question is about django-sass-processor, not django-libsass.
