### ISSUE TITLE
django_libsass.SassCompiler broken with libsass==0.19.3

### ISSUE THREAD

**Issue by michaeljonaitis** [torchbox/django-libsass#33]
On October 5th libsass was updated to 0.19.3, I am not exactly sure what it is but it manage.py compress hangs until libsass==0.19.2 is specified as a pip requirement. Looking into it deeper today.

**Comment by gasman** [comment]
0.19.3 seems to be working fine here (with OS X 10.14.6, Python 3.7.2, Django 3.0.2, django-compressor 2.4) - closing as unable to replicate.
