### ISSUE TITLE
Standard deployment strategies

### ISSUE THREAD

**Issue by smvoss** [torchbox/django-libsass#36]
First off, I love the library.

I am looking to deploy with django + whitenoise, and I noticed that if I don't already have the scss compiled when the server starts, the file server (in this case, whitenoise) does not notice the compiled, now cached, css file.

Now, at the root of the problem this is due to how whitenoise handles its dependencies (cache, only static that exists at launch time are recognized), however I am wondering how you recommend using this to get around that issue (possibly a different type of static file serving?). I can get around this with `WHITENOISE_AUTOREFRESH = True` which allows it to check any new staticfiles that show up, but it is not recommended to do this.

I also tried using `s3` to host my staticfiles, however after digging deep into the dependency chain, one of them (I don't remember which anymore) specifically checks if the default store is network and if so, don't create the file there. It instead just creates it locally and without a `collectstatic` is never pushed over to the static root.

In every scenario I tried I would have to either manually intervene after each css has been compiled (by either restarting the server or running `collectstatic`). Any guidance would be appreciated.

**Comment by gasman** [comment]
Hi @smvoss - afraid I don't have any advice on approaches to deployment, as that's more in the realm of django-compressor rather than django-libsass.
