### ISSUE TITLE
Single vs double quotes @import

### ISSUE THREAD

**Issue by loren-jiang** [torchbox/django-libsass#38]
libsass==0.19.4
Django==3.0.5
django-libsass==0.8
django-compressor==2.4

Noticed as small quirk in trying to import scss files

>@import "materialize-src/sass/materialize"; 
>// single quotes not working
>// @import 'materialize-src/sass/materialize';

**Comment by gasman** [comment]
Hi @loren-jiang,
I'm unable to replicate any problems with single or double quotes in import lines. Starting from the [hello-django-libsass](https://github.com/gasman/hello-django-libsass) project, I created a file `hello/static/css/materialize-src/sass/materialize.scss`, containing

    h1 {
        border: 10px solid blue;
    }

and then added

    @import 'materialize-src/sass/materialize';

to the top of `hello/static/css/index.scss`. The import worked successfully with single or double quotes, and added a blue border to the h1.

If you can show a minimal example that demonstrates the issue, I'll be happy to investigate further.
