### ISSUE TITLE
Does this support django 3.1?

### ISSUE THREAD

**Issue by arlyxiao** [torchbox/django-libsass#40]
'compress'. Did you forget to register or load this tag?
```
{% compress css %}
    <link rel="stylesheet" type="text/x-scss" href="{% static "myapp/css/main.scss" %}" />
{% endcompress %}
```

**Comment by gasman** [comment]
You need `{% load compress %}` at the top of your template.

(Have just tested [hello-django-libsass](https://github.com/gasman/hello-django-libsass) against Django 3.1, and all works fine)
