### ISSUE TITLE
Discrepancy with django-libsaas vs. npm's sass

### ISSUE THREAD

**Issue by morsik** [torchbox/django-libsass#53]
Not sure if this is a bug or not to be honest.

I have this piece of code I just imported into django-libsass/django_compressor which didn't worked. The `$value` wasn't correctly substituted at compilation time:

```scss
@each $variant in ['', 'x', 's'] {
  @each $spacer, $value in $spacers {
    .p#{$variant}-#{$spacer} > .stripe::before,
    {
      width: #{calc($value * 3 / 5)};
      margin-left: -#{$value};
    }
  }
}
```

And the CSS generated was:
```css
.p-5 > .stripe::before {
  width: calc($value * 3 / 5);
  margin-left: -3rem; }
```

Code above compiles correctly when compiling with Grunt using those libraries:

```json
{
  "dependencies": {
    "bootstrap": "^5.3.1",
    "jquery": "^3.7.0"
  },
  "devDependencies": {
    "grunt": "^1.6.1",
    "grunt-contrib-copy": "^1.0.0",
    "grunt-contrib-sass": "^2.0.0",
    "grunt-purgecss": "^5.0.0",
    "sass": "^1.64.2"
  }
}
```

But I was able to fix this in to compile correctly with django-libsaas with simple change to offending line (just wrapping var inside `#{}`) to:

```scss
      width: #{calc(#{$value} * 3 / 5)};
```

Not sure if this should work out of the box (spec-wise) or I what I had earlier with Grunt-based project was just outside of SCSS spec.

**Comment by gasman** [comment]
Hi @morsik,
The SASS compilation is handled by the underlying [libsass](https://sass-lang.com/libsass/) library, which does not promise to be feature-complete against the Node SASS implementation (and is now deprecated, so this is unlikely to change in future):

> LibSass is an implementation of Sass in C/C++, designed to be easy to integrate into many different languages. However, as time wore on it ended up lagging behind [Dart Sass](https://sass-lang.com/dart-sass) in features and CSS compatibility. LibSass is now deprecated—new projects should use Dart Sass instead.

**Comment by morsik** [comment]
@gasman thanks for explanation! I just found that info too few minutes ago :(
