### ISSUE TITLE
Support source maps

### ISSUE THREAD

**Issue by timtan** [torchbox/django-libsass#7]
Thanks for the good package.

Is it possible django-libsass support more parameter which libsass-python support?

such as source map, it may be very useful.

**Comment by jorge-marques** [comment]
:+1:

**Comment by gasman** [comment]
Have edited this issue title to be specifically about source maps - other parameters would have to be considered on a case-by-case basis (and may not make sense for all options - for example, I don't think there's much point supporting arbitrary include paths, when Django's 'finder' mechanism does that job perfectly well).

Source maps are a bit tricky. Passing the option to libsass-python is not enough - we also need to make sure they get saved to a location that's compatible with django-compressor. As [described here](https://groups.google.com/d/msg/wagtail/WSiYYM82vkA/yrsYeeisvDUJ), django-compressor's current design doesn't accommodate this well - it assumes that precompilers will take a single input stream, and produce a single stream of CSS as output.

**Comment by gasman** [comment]
Source maps implemented in #13.
